Repository iamshubhamg/Leet-Code, pull requests merged in 2022-10, with the labels that each got.

#224 Added Floyd-warshall.cpp
  FloydWarshell.cpp
Labels: hacktoberfest-accepted

#223 Create Kadane'sAlgorithm.cpp
  Kadane'sAlgorithm.cpp
Labels: hacktoberfest-accepted

#222 Create FloydWarshall-AllPairShortestPath.c
  FloydWarshall-AllPairShortestPath.c
Labels: hacktoberfest-accepted

#220 Create Sum of Series.py
  Sum of Series.py
Labels: hacktoberfest-accepted

#216 Create coin path
  coin path
Labels: hacktoberfest-accepted

#214 Create array consecutive
  array consecutive
Labels: hacktoberfest-accepted

#206 Create Power of base and exponent
  Power of base and exponent
Labels: hacktoberfest-accepted

#205 Create Finding the pivot index
  Finding the pivot index
Labels: hacktoberfest-accepted

#203 Create Climbing the upstairs
  Climbing the upstairs
Labels: hacktoberfest-accepted

#231 Create Peak_element.cpp
  Peak_element.cpp
Labels: hacktoberfest-accepted

#230 Create Kadanes_Algorithm.cpp
  Kadanes_Algorithm.cpp
Labels: hacktoberfest-accepted

#228 Create Subarray_with_given_sum.cpp
  Subarray_with_given_sum.cpp
Labels: hacktoberfest-accepted

#227 Create cycle-detection-bfs.cpp
  cycle-detection-bfs.cpp
Labels: hacktoberfest-accepted

#229 Create Minimum_number_of_jumps.cpp
  Minimum_number_of_jumps.cpp
Labels: hacktoberfest-accepted

#201 Create Two sorted arrays median
  Two sorted arrays median
Labels: hacktoberfest-accepted

#226 95. Unique Binary Search Trees II
  95-Unique-Binary-Search-Trees-II.cpp
Labels: hacktoberfest-accepted

#207 Create Combining the two tables
  Combining the two tables
Labels: hacktoberfest-accepted

#218 Create design sql
  design sql
Labels: hacktoberfest-accepted

#225 215. Kth Largest Element in an Array
  KthLargest.java
Labels: hacktoberfest-accepted

#221 Create stack using list.py
  stack using list.py
Labels: hacktoberfest-accepted

#235 added bitwise xor of all pairings
  Bitwise XOR of All Pairings.cpp
Labels: hacktoberfest-accepted

#234 Create leetcode 2435: Paths in Matrix Whose Sum Is Divisible by K.cpp
  leetcode 2435: Paths in Matrix Whose Sum Is Divisible by K.cpp
Labels: hacktoberfest-accepted

#233 19.Remove Nth Node from End of List
  19.Remove Nth Node from End of List
Labels: hacktoberfest-accepted

#232 Expression Matching leetcode
  Expressionmatching.cpp
Labels: hacktoberfest-accepted

#217 Create alphabet board
  alphabet board
Labels: hacktoberfest-accepted

#213 Create partition of arrays
  partition of arrays
Labels: hacktoberfest-accepted

#211 Create price discount
  price discount
Labels: hacktoberfest-accepted

#242 Create 2-keys-keyboard.cpp
  2-keys-keyboard.cpp
Labels: hacktoberfest-accepted

#241 Create createtwosums.cs
  createtwosums.cs
Labels: hacktoberfest-accepted

#245 Create average-height-of-buildings-in-each-segment.cpp
  average-height-of-buildings-in-each-segment.cpp
Labels: enhancement, hacktoberfest-accepted

#244 Create alien-dictionary.cpp
  alien-dictionary.cpp
Labels: hacktoberfest-accepted

#243 Create 1-bit-and-2-bit-characters.cpp
  1-bit-and-2-bit-characters.cpp
Labels: hacktoberfest-accepted

#239 Create 3sum
  3sum
Labels: hacktoberfest-accepted

#202 Create Searching for Insert position
  Searching for Insert position
Labels: hacktoberfest-accepted

#252 Create hamming.cpp
  hamming.cpp
Labels: hacktoberfest-accepted

#251 Create coinchange.cpp
  coinchange.cpp
Labels: hacktoberfest-accepted

#250 Create sumof1d.cpp
  sumof1d.cpp
Labels: hacktoberfest-accepted

#249 Create satisfactiom.cpp
  satisfactiom.cpp
Labels: hacktoberfest-accepted

#248 Added Minimum Path Sum solution with explanation
  minimum_path_sum.cpp
Labels: hacktoberfest-accepted

#256 Create countprimes.cpp
  countprimes.cpp
Labels: hacktoberfest-accepted

#255 Create traversal.cpp
  traversal.cpp
Labels: hacktoberfest-accepted

#254 Create 3d.cpp
  3d.cpp
Labels: hacktoberfest-accepted

#253 Create binary.cpp
  binary.cpp
Labels: hacktoberfest-accepted

#270 Create fiest_push.py
  fiest_push.py
Labels: hacktoberfest-accepted

#279 Create string_tointeger.cpp
  string_tointeger.cpp
Labels: hacktoberfest-accepted

#278 Create longest_pallindrome.cpp
  longest_pallindrome.cpp
Labels: hacktoberfest-accepted

#277 Create reverse_ds.cpp
  reverse_ds.cpp
Labels: hacktoberfest-accepted

#276 Update README.md
  README.md
Labels: hacktoberfest-accepted

#275 Leetcode problem unique paths 2 solution with explanation
  unique_paths_ii.cpp
Labels: hacktoberfest-accepted

#273 Create tree.cpp
  tree.cpp
Labels: hacktoberfest-accepted

#272 Create swap.py
  swap.py
Labels: hacktoberfest-accepted

#271 Create heap.py
  heap.py
Labels: hacktoberfest-accepted

#269 Create merging.py
  merging.py
Labels: hacktoberfest-accepted

#268 Create job.py
  job.py
Labels: hacktoberfest-accepted

#267 Create build.py
  build.py
Labels: hacktoberfest-accepted

#266 Create tree_heright.cpp
  tree_heright.cpp
Labels: hacktoberfest-accepted

#265 Create stack_with.cpp
  stack_with.cpp
Labels: hacktoberfest-accepted

#264 Create process_package.cpp
  process_package.cpp
Labels: hacktoberfest-accepted

#263 Create max_Sliding.cpp
  max_Sliding.cpp
Labels: hacktoberfest-accepted

#262 Create check_brackets.cpp
  check_brackets.cpp
Labels: hacktoberfest-accepted

#261 Create 2444. Count Subarrays With Fixed Bounds
  2444. Count Subarrays With Fixed Bounds
Labels: enhancement, help wanted, good first issue, hacktoberfest-accepted

#260 Create hacktober.cpp
  hacktober.cpp
Labels: hacktoberfest-accepted

#259 Create solution.cpp
  solution.cpp
Labels: hacktoberfest-accepted

#258 Create test.cpp
  test.cpp
Labels: hacktoberfest-accepted

#257 Create add.cpp
  add.cpp
Labels: hacktoberfest-accepted

#247 1255 leetcode.cpp
  1255 leetcode.cpp
Labels: hacktoberfest-accepted

#246 Push Dominoes Problem
  838. Push Dominoes.java
Labels: hacktoberfest-accepted

#240 adding imp leetcode dsa questions
  dsa leetcode problems/delete_node_in_a_linked_list.cpp
  dsa leetcode problems/distinct-subsequences.cpp
  dsa leetcode problems/generate_parenthesis.cpp
  dsa leetcode problems/letter_tile_possibilities.cpp
  dsa leetcode problems/linked_list_cycle.cpp
  dsa leetcode problems/merge_2_sorted_lists.cpp
  dsa leetcode problems/middle_of_a_linked_list.cpp
  dsa leetcode problems/path_sum_2.cpp
  dsa leetcode problems/path_sum_3.cpp
  dsa leetcode problems/plus_one.cpp
  dsa leetcode problems/remove_duplicated_from_sorted_list.cpp
  dsa leetcode problems/remove_linked_list_elements.cpp
  dsa leetcode problems/reverse_linked_list.cpp
  dsa leetcode problems/sort_colors.cpp
  dsa leetcode problems/ugly_numbers_2.cpp
Labels: hacktoberfest-accepted

#237 binary search program added
  Binary_search.cpp
Labels: hacktoberfest-accepted

#210 Create Removing unused code for project
  Removing unused code for project
Labels: hacktoberfest-accepted

#208 Create Number of 1 bits
  Number of 1 bits
Labels: hacktoberfest-accepted

#204 Create Increment array by plus one
  Increment array by plus one
Labels: hacktoberfest-accepted

#281 Number of Subarrays With GCD Equal to K
  "Guess the number" game
  Count and say problem.
  dsa leetcode problems/Number of Subarrays With GCD Equal to K.cpp
  leetcode 2435: Paths in Matrix Whose Sum Is Divisible by K.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#280 Create 645.SetMismatch.java
  645.SetMismatch.java
Labels: bug, hacktoberfest-accepted

#286 Create Binary_Search.cpp
  dsa leetcode problems/Binary_Search.cpp
Labels: hacktoberfest-accepted

#285 Create Power_of_Three.cpp
  dsa leetcode problems/Power_of_Three.cpp
Labels: hacktoberfest-accepted

#284 Create Two_Sum.cpp
  dsa leetcode problems/Two_Sum.cpp
Labels: hacktoberfest-accepted

#283 Create Remove_Duplicates_from_Sorted_Array.cpp
  dsa leetcode problems/Remove_Duplicates_from_Sorted_Array.cpp
Labels: hacktoberfest-accepted

#282 Create Palindrome_Number.cpp
  dsa leetcode problems/Palindrome_Number.cpp
Labels: hacktoberfest-accepted

#287 Create Roman_to_integer.cpp
  dsa leetcode problems/Roman_to_integer.cpp
Labels: hacktoberfest-accepted

#288 Create separatenumbers.py
  separatenumbers.py
Labels: good first issue, hacktoberfest-accepted

#289 Added cpp code for next permutation
  Next Permutation.cpp
Labels: hacktoberfest-accepted

#290 adding leetcode 105 construct binary tree from preorder and inorder t…
  105_construct_binary_tree_from_preorder_and_inorder_traversal.cpp
  199_binary_tree_right_side_view.cpp
  binary_search.cpp
Labels: good first issue, hacktoberfest-accepted

#291 adding leetcode 199 binary tree right side view
  199_binary_tree_right_side_view.cpp
Labels: hacktoberfest-accepted

#294 Added Cpp code for traveling salesman problem
  Travelling Salesman.cpp
Labels: hacktoberfest-accepted

#293 readme: improve writing
  README.md
Labels: hacktoberfest-accepted

#292 adding leetcode 236 lowest common ancestor of a binary tree
  236_lowest_common_ancestor_of_a_binary_tree.cpp
Labels: hacktoberfest-accepted

#296 Create operation.cs
  operation.cs
Labels: hacktoberfest-accepted

#295 Create swap.cs
  swap.cs
Labels: hacktoberfest-accepted

#298 Create rowcount.cs
  rowcount.cs
Labels: hacktoberfest-accepted

#297 Create readline.cs
  readline.cs
Labels: hacktoberfest-accepted

#299 Create Check_If_Array_Is_Sorted_And_Rotated.cpp
  dsa leetcode problems/Check_If_Array_Is_Sorted_And_Rotated.cpp
Labels: hacktoberfest-accepted

#304 Create Subarray_Product_Less_Than_K.cpp
  dsa leetcode problems/Subarray_Product_Less_Than_K.cpp
Labels: hacktoberfest-accepted

#303 Create Remove_Element.cpp
  dsa leetcode problems/Remove_Element.cpp
Labels: hacktoberfest-accepted

#302 Create Valid_Parentheses.cpp
  dsa leetcode problems/Valid_Parentheses.cpp
Labels: hacktoberfest-accepted

#301 Create Sqrt(x).cpp
  dsa leetcode problems/Sqrt(x).cpp
Labels: hacktoberfest-accepted

#300 Create Sort_Array_By_Increasing_Frequency.cpp
  dsa leetcode problems/Sort_Array_By_Increasing_Frequency.cpp
Labels: hacktoberfest-accepted

#305 pascal-triangle leetcode solution
  pascal-triangle.cpp
Labels: hacktoberfest-accepted

#310 Create fact.cs
  fact.cs
Labels: hacktoberfest-accepted

#309 Create palidrome.cs
  palidrome.cs
Labels: hacktoberfest-accepted

#311 Create reverse.cs
  reverse.cs
Labels: hacktoberfest-accepted

#308 Create testrun.cs
  testrun.cs
Labels: hacktoberfest-accepted

#307 Added Python Solutions for few Leetcode Problems
  1328_Break_a_Palindrome.py
  623_Add_One_Row_to_Tree.py
  981_Time_Based_Key-Value_Store.py
Labels: hacktoberfest-accepted

#306 Added LeetCode 179. Largest Number
  179_Largest-Number.cpp
Labels: hacktoberfest-accepted
